### ISSUE TITLE
OSX build of latest version

### ISSUE THREAD

**Issue by Penhorse** [Penhorse/Instrument-Browser#10]
@bafonso @dhatadi

I have updated to JUCE 4.2.1 and added some feature requests #7 and #9. The current version is now 1.4.0

If either of you wants to do a new OSX build I will update the user library package :)

**Comment by dhatadi** [comment]
Great stuff, seems to work well. New build attached.

[ Instrument Browser 1.4.0 OSX 10.9+ x64.zip](https://github.com/Penhorse/Instrument-Browser/files/344992/Instrument.Browser.1.4.0.OSX.10.9.x64.zip)

**Comment by Penhorse** [comment]
Thanks dhatadi!
