### ISSUE TITLE
OSX build of v1.5.0

### ISSUE THREAD

**Issue by Penhorse** [Penhorse/Instrument-Browser#13]
@bafonso @dhatadi

Hello gents hope you're both well :)

The Reaktor 6.0.3 update introduced a change to the format of newly saved ism files so I've updated ismsnoop to handle the new format.

When somebody gets a chance to build an OSX version I will update the user library package again!

**Comment by Penhorse** [comment]
Found a Mac at work that I can use, so I'm going to do it myself :)

**Comment by Penhorse** [comment]
Build attached. Will update user library entry tonight.
[Instrument.Browser.1.5.0.OSX.10.9x64.zip](https://github.com/Penhorse/Instrument-Browser/files/469523/Instrument.Browser.1.5.0.OSX.10.9x64.zip)

**Comment by dhatadi** [comment]
Nice work, @Penhorse. I'm in the middle of relocating so I don't have all my gear.

**Comment by Penhorse** [comment]
No problem hope the move goes well ;)
