### ISSUE TITLE
OSX version

### ISSUE THREAD

**Issue by Penhorse** [Penhorse/Instrument-Browser#6]
Configure an OSX build using Introjucer and release a build. Possibly requires some changes to Penhorse/rtw to support OSX.

**Comment by bafonso** [comment]
You can find the 1.3.2 pre-release here: 

https://github.com/bafonso/Instrument-Browser/releases/tag/v1.3.2

I'll need to change the binary, it still says 1.3.1... Anyway, I just downloaded the latest JUCE (4.2.2) and it updated your files that were 3.xx I believe. Not sure this is an issue or not. I have never really used JUCE before, I'm quite amazed I could port this during this morning. yay to hipsters in macs! :-)

**Comment by Penhorse** [comment]
Great thanks bafonso. If you're happy that this build is working i could add it to the user library package? Or if you like you can upload it as a separate user library entry and manage the mac builds yourself, mark it as (Mac) and I'll label mine with (Windows). Not sure which is the best option

When i get a chance i'll update my version of juce and merge your fork back into the master so we are in sync

**Comment by bafonso** [comment]
You can definitely add it to the user library! Let me know if I can help with the merge. If you can open my updated tree w/ juce 4.2.2 you should be ready to go

**Comment by Penhorse** [comment]
7112007526e8e5c633f5ff84dfb19ad51d18a090
